/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.*;
import Clases.SqlUsuarios;
import Clases.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class From_Login extends javax.swing.JFrame {
private int intentos;
    public From_Login() {
     initComponents();
      this.setLocationRelativeTo(null);
      TxtUsuario.setBackground(new java.awt.Color(0,0,0,1)); // Texto Trasparente
      Txt_Contra.setBackground(new java.awt.Color(0,0,0,1)); // Texto Trasparente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Jlabel_Login = new javax.swing.JLabel();
        jLabel_Frase = new javax.swing.JLabel();
        jLabel_Usu = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_Contra = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Txt_Contra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Usu1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Fondo2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlabel_Login.setFont(new java.awt.Font("Street Corner Bold", 0, 36)); // NOI18N
        Jlabel_Login.setForeground(new java.awt.Color(204, 204, 0));
        Jlabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel_Login.setText("Login");
        jPanel1.add(Jlabel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 40));

        jLabel_Frase.setFont(new java.awt.Font("Street Corner", 0, 14)); // NOI18N
        jLabel_Frase.setForeground(new java.awt.Color(204, 204, 0));
        jLabel_Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Frase.setText("Hola, Comencemos ");
        jLabel_Frase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel_Frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, -1));

        jLabel_Usu.setFont(new java.awt.Font("Street Corner Bold", 1, 13)); // NOI18N
        jLabel_Usu.setForeground(new java.awt.Color(204, 204, 0));
        jLabel_Usu.setText("Usuario");
        jPanel1.add(jLabel_Usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 360, 10));

        jLabel_Contra.setFont(new java.awt.Font("Street Corner Bold", 1, 13)); // NOI18N
        jLabel_Contra.setForeground(new java.awt.Color(204, 204, 0));
        jLabel_Contra.setText("Contraseña");
        jPanel1.add(jLabel_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, -1));

        TxtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        TxtUsuario.setForeground(new java.awt.Color(204, 204, 0));
        TxtUsuario.setBorder(null);
        TxtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        TxtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TxtUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 30));

        jLabel5.setFont(new java.awt.Font("Street Corner", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Olvidaste la Contraseña?");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 390, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Street Corner", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 0));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 340, 30));

        Txt_Contra.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Contra.setFont(new java.awt.Font("Street Corner", 0, 12)); // NOI18N
        Txt_Contra.setForeground(new java.awt.Color(204, 204, 0));
        Txt_Contra.setBorder(null);
        Txt_Contra.setCaretColor(new java.awt.Color(204, 204, 0));
        jPanel1.add(Txt_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/textura-marmol-blanco-negro.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 440, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Usu1.setFont(new java.awt.Font("Street Corner Bold", 1, 13)); // NOI18N
        jLabel_Usu1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel_Usu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Licoreria Jhon y Haider Logo  (Registro).png"))); // NOI18N
        jPanel2.add(jLabel_Usu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 260, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/textura-marmol-blanco (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         Inicio.frmLog = null; 
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
SqlUsuarios modSql = new SqlUsuarios();
Usuarios mod = new Usuarios();

String pass = new String(Txt_Contra.getPassword());
if(!TxtUsuario.getText().equals("") && !pass.equals("")){
//String nuevoPass = hash.sha1(pass);
    
    mod.setUsuario(TxtUsuario.getText());
    mod.setContraseña(pass);
    //mod.setContraseña(hash.sha1(pass));
     if (modSql.Login(mod)) {
         Inicio.frmLog = null;
         this.dispose();
         
         Menu frmMenu = new Menu (mod);
         frmMenu.setVisible(true);
        //Home frmHome = new Home(mod);
        //frmHome.setVisible(true);
         
     } else if (intentos == 3) {
                JOptionPane.showMessageDialog(null, "Haz Exedido el numero de intentos");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(null,
                        "Error, el Usuario y contrasela es INCORRECTO, Intente nuevamente \n quedan "
                                + (3 - intentos) + " intentos ");
                intentos++; // Incrementar la variable intentos en 1
            }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_Login;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JPasswordField Txt_Contra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Contra;
    private javax.swing.JLabel jLabel_Frase;
    private javax.swing.JLabel jLabel_Usu;
    private javax.swing.JLabel jLabel_Usu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
